#!/bin/bash

if [ -z "$VHOST" ]
then
  echo VHOST is not set, exiting...
  exit 1
fi

IFACE_NAME=${IFACE_NAME:-eth0}
PORT=${PORT:-5000}
ETCD_KEY=${ETCD_KEY:-nginx_proxy}
ETCD_REDIRECT_KEY=${ETCD_KEY:-nginx_www_redirect_domains}
UUID=$(cat /proc/sys/kernel/random/uuid)

while true
do
  IPADDR=$(ip addr show dev $IFACE_NAME | grep " inet " | awk '{print $2}' | cut -d'/' -f 1)

  if [ $(echo $VHOST | egrep -c "^www\.") -gt 0 ] > /dev/null
  then
    curl -sSL -o /dev/null -XPUT -d "ttl=10" -d "value=$IPADDR:$PORT" http://etcd:4001/v2/keys/$ETCD_KEY/${VHOST#www.}/$UUID
    curl -sSL -o /dev/null -XPUT -d "ttl=10" -d "value=true" http://etcd:4001/v2/keys/$ETCD_REDIRECT_KEY/${VHOST#www.}
  else
    curl -sSL -o /dev/null -XPUT -d "ttl=10" -d "value=$IPADDR:$PORT" http://etcd:4001/v2/keys/$ETCD_KEY/$VHOST/$UUID
  fi
  sleep 5
done
