#!/bin/bash

if [ -z "$VHOST" ]
then
    echo VHOST is not set, exiting...
    exit 1
fi

while true
do
    curl -sSL -d "ttl=10" -d "value=$(ip addr show dev eth0 | grep " inet " | awk '{print $2}' | cut -d'/' -f 1):5000" http://$(ip route show dev eth0 | grep default | awk '{print $3}')/v2/keys/nginx_proxy/$VHOST/$(hostname)
    sleep 5
done
